[package]
name = "listening-room"
version = "0.1.0"
description = "A spatial Spotify listening room"
edition = "2024"

[lib]
name = "listening_room_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
dotenvy = "0.15.7"
env_logger = "0.11.11"
futures = "0.3.31"
librespot = { version = "0.8.0", default-features = false, features = ["rodio-backend", "rustls-tls-native-roots", "with-libmdns"] }
librespot-oauth = { version = "0.8.0", default-features = false, features = ["rustls-tls-native-roots"] }
log = "0.4.34"
rspotify = { version = "0.16.1", features = ["cli"] }
rustfft = "6.4.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tokio = { version = "1", features = ["sync"] }

[target.'cfg(windows)'.dependencies]
wasapi = "0.24.0"
